name = "app-mega-license-worker"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "LICENSES"
id = "43451bd0f7334523a25513d8bc6001cd"          # output of: wrangler kv namespace create LICENSES

[triggers]
crons = ["0 */4 * * *"]            # every 4h

[vars]
GITHUB_REPO = "omniforgebr/app-mega-licenses"
KID = "of-license-2026"
SEAT_PUBLIC_KEY = "lIC23JHeNPN3+/KmUSBDVMVBWv2QokOrwXj/MgVUKmg="   # raw base64 (par da SIGNING_KEY) — saida do keygen

[[d1_databases]]
binding = "SEATS_DB"
database_name = "app-mega-seats"
database_id = "5460d0f9-b807-47c2-b3ac-4545c048d2b3"
